import type { AnalysisResult } from '@/types';

export function generateReportMarkdown(
  result: AnalysisResult,
  jobTitle: string,
  companyName: string,
): string {
  const lines: string[] = [];

  lines.push(`# ColdTailor AI - Analysis Report`);
  lines.push('');
  lines.push(`**Role:** ${jobTitle || 'N/A'}`);
  lines.push(`**Company:** ${companyName || 'N/A'}`);
  lines.push(`**Date:** ${new Date().toLocaleDateString()}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  lines.push(`## ATS Match Score: ${result.atsScore}/100`);
  lines.push('');

  lines.push('## Missing Keywords');
  if (result.missingKeywords.length > 0) {
    result.missingKeywords.forEach((kw) => lines.push(`- ${kw}`));
  } else {
    lines.push('No critical keywords missing.');
  }
  lines.push('');

  lines.push('## Tailored Resume Bullets');
  result.tailoredBullets.forEach((b, i) => lines.push(`${i + 1}. ${b}`));
  lines.push('');

  lines.push('## LinkedIn Note');
  lines.push(`(${result.linkedInNote.length}/300 characters)`);
  lines.push('```');
  lines.push(result.linkedInNote);
  lines.push('```');
  lines.push('');

  lines.push('## Cold Email');
  lines.push(`**Subject:** ${result.coldEmail.subject}`);
  lines.push('```');
  lines.push(result.coldEmail.body);
  lines.push('```');
  lines.push('');

  lines.push('## Follow-Up (Day 4)');
  lines.push('```');
  lines.push(result.followUpNote);
  lines.push('```');
  lines.push('');

  lines.push('---');
  lines.push('*Generated by ColdTailor AI*');

  return lines.join('\n');
}

export function downloadFile(filename: string, content: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
